"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import store from "../Redux/State/store";
import { Provider } from "react-redux";
import { NextUIProvider } from "@nextui-org/system";
import { Toaster } from "sonner";
import Image from "next/image";

import success from "../public/Images/Notifications/success.png";
import info from "../public/Images/Notifications/info.png";
import warning from "../public/Images/Notifications/warning.png";
import error from "../public/Images/Notifications/error.png";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          {children}
          <Toaster
            // invert
            expand={true}
            closeButton
            duration={3000}
            icons={{
              success: <Image src={success} alt="success" />,
              info: <Image src={info} alt="info" />,
              warning: <Image src={warning} alt="warning" />,
              error: <Image src={error} alt="error" />,
            }}
          />
        </body>
      </html>
    </Provider>
  );
}
